spring.application.name=demo

spring.thymeleaf.cache=false

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=10MB

spring.servlet.multipart.max-request-size=10MB


server.port=8081
server.servlet.context-path=/med-manager

# Thong tin benh vien (Doc bang @Value)
app.hospital.name=Rikkei International Hospital
app.upload.path=/images/

file.upload-dir=${user.home}/rikkei-uploads/
